=== StormForgeDeveloper/StormForge/Tools/Src/SFResultCodeCompiler/xsd/SFResultCode.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

  <xs:simpleType name="Severity" final="restriction" >
    <xs:restriction base="xs:string">
      <xs:enumeration value="Success" />
      <xs:enumeration value="Informational" />
      <xs:enumeration value="Warning" />
      <xs:enumeration value="Error" />
    </xs:restriction>
  </xs:simpleType>
  
  
	<xs:element name="ResultCodes">
		<xs:complexType>
			<xs:sequence>
        <xs:element name="ResultCodeItem" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
            <xs:attribute name="Severity" type="Severity" use="required" />
            <xs:attribute name="CodeName" type="xs:string" use="required"/>
            <xs:attribute name="Desc" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="Facility" type="xs:string" use="required" />
      <xs:attribute name="Custom" type="xs:boolean" use="optional" default="true" />
      <xs:attribute name="UseFacilityName" type="xs:boolean" use="optional" default="true" />
      <xs:attribute name="IDTable" type="xs:boolean" use="optional" default="false" />
    </xs:complexType>
	</xs:element>

</xs:schema>

=== StormForgeDeveloper/StormForge/Engine/Data/ResultCode/ResultCodeGame.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ResultCodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="SFResultCode.xsd"
             Facility="Game"
             IDTable="true"
             >


	<ResultCodeItem Severity="Error" CodeName="ALREADY_IN_GAME" Desc="User is already in a game"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_PLAYER" Desc="Invalid player"/>
	<ResultCodeItem Severity="Error" CodeName="NOTREADY" Desc="Game is not ready"/>

	<ResultCodeItem Severity="Error" CodeName="INVALID_PLAYER_STATE" Desc="Invalid player state to do the action"/>
	<ResultCodeItem Severity="Error" CodeName="NO_MATCHING_HARVEST_ID" Desc="Failed to find matching harvest id"/>

	<ResultCodeItem Severity="Error" CodeName="INVALID_SHOPITEM" Desc="Invalid shop item data"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_SHOPITEMID" Desc="Invalid shop item id"/>

	<ResultCodeItem Severity="Error" CodeName="ALREADY_IN_PARTY" Desc="User is already in a party"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_PARTYID" Desc="Invalid partyID"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_PLAYER_COUNT" Desc="Invalid player count for game"/>

	<ResultCodeItem Severity="Error" CodeName="NO_PRIVILEGE" Desc="User doesn't have eligible privilege"/>
	<ResultCodeItem Severity="Error" CodeName="NOTENOUGH_RESOURCE" Desc="Not enough money(gold, gem, etc)"/>
	<ResultCodeItem Severity="Error" CodeName="MAX_NOTIFICATION" Desc="Maximum notification count"/>
	<ResultCodeItem Severity="Error" CodeName="MAX_TRY" Desc="Maximum try reached"/>

	<ResultCodeItem Severity="Error" CodeName="ALREADY_IN_CHAT" Desc="User is already in a chatting channel"/>

	<ResultCodeItem Severity="Error" CodeName="MAPOBJECT_INVALID" Desc="Map object is invalid"/>
	<ResultCodeItem Severity="Error" CodeName="OCCUPIED_MAPOBJECT_IS_REQUIRED" Desc="Map object is required to be occupied"/>
	<ResultCodeItem Severity="Error" CodeName="MAPOBJECT_ALREADY_IN_USE" Desc="Map object is already in use"/>
	<ResultCodeItem Severity="Error" CodeName="MAPOBJECT_NOT_IN_USE" Desc="Map object is not in use"/>
	<ResultCodeItem Severity="Error" CodeName="MAPOBJECT_NOT_FOUND" Desc="Map object not found"/>
	<ResultCodeItem Severity="Error" CodeName="MAPOBJECT_NOT_OCCUPIED_BY_PLAYER" Desc="Map object is not occupied by the player"/>

	<ResultCodeItem Severity="Error" CodeName="INVALID_NPCID" Desc="Invalid NPC id"/>
	<ResultCodeItem Severity="Error" CodeName="UNEXPECTED_TABLE_VALUE" Desc="Unexpected table value"/>
	<ResultCodeItem Severity="Error" CodeName="NOT_ENOUGH_CURRENCY" Desc="Not enough currency"/>
    <ResultCodeItem Severity="Error" CodeName="NOT_ENOUGH_STAMINA" Desc="Not enough stamina"/>

    <ResultCodeItem Severity="Error" CodeName="PLAYER_IS_BUSY" Desc="The player is busy"/>
    <ResultCodeItem Severity="Error" CodeName="PLAYER_TOO_FAR_AWAY" Desc="The player is too far away"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_GOLD_VALUE" Desc="Invalid gold value has been specified"/>

    <!--Legacy error codes-->
	<ResultCodeItem Severity="Error" CodeName="INVALID_ROLE" Desc="Invalid player role"/>
	<ResultCodeItem Severity="Error" CodeName="NOT_READY_FOR_NEXT_STATE" Desc="Not ready for next game play state"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_VOTETYPE" Desc="Invalid vote type"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_VOTE_STATE" Desc="Invalid vote state"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_VOTE_TARGET" Desc="Invalid vote target"/>
	<ResultCodeItem Severity="Error" CodeName="NO_SUFFRAGE" Desc="No suffrage"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_GAMESTATE" Desc="Invalid game state"/>
	<ResultCodeItem Severity="Error" CodeName="LOW_STAMINA" Desc="Doesn't have enough stamina"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_COSTID" Desc="Invalid cost table id"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_BOTTALK_TABLE" Desc="Invalid bot talk table"/>
    
    <ResultCodeItem Severity="Error" CodeName="REQUEST_HAS_EXPIRED" Desc="Request has expired"/>

    <ResultCodeItem Severity="Error" CodeName="GROUP_OBJECT_NOT_FOUND" Desc="Group object not found"/>

</ResultCodes>

=== StormForgeDeveloper/StormForge/Engine/Data/ResultCode/ResultCodeNet.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ResultCodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="SFResultCode.xsd"
             Facility="Net"
             IDTable="false"
             >

  
  <ResultCodeItem Severity="Success" CodeName="PROCESSED_SEQUENCE" Desc="Network sequence already processed"/>
  <ResultCodeItem Severity="Error" CodeName="PROTOCOL_VERSION_MISMATCH" Desc="The version not available or miss match with system."/>
  <ResultCodeItem Severity="Error" CodeName="NOTINITIALIZED" Desc="Network is not initialized"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_NETCLASS" Desc="The version not available or miss match with system."/>
  <ResultCodeItem Severity="Error" CodeName="NOT_ENOUGH_WINDOWSPACE" Desc="Not enough space in sliding window"/>
  <ResultCodeItem Severity="Error" CodeName="IO_ABORTED" Desc="Network IO aborted"/>
  <ResultCodeItem Severity="Error" CodeName="IO_SEND_FAIL" Desc="Network IO send failed"/>
  <ResultCodeItem Severity="Error" CodeName="IO_RECV_FAIL" Desc="Network IO recv failed"/>
  <ResultCodeItem Severity="Error" CodeName="SEND_FAIL" Desc="Network send failed"/>
  <ResultCodeItem Severity="Error" CodeName="RECV_FAIL" Desc="Network recv failed"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_SEQUENCE" Desc="Network Message sequence is invalid"/>
  <ResultCodeItem Severity="Error" CodeName="BADPACKET_SIZE" Desc="Network Message not expected bad packet size"/>
  <ResultCodeItem Severity="Error" CodeName="CONNECTION_CLOSED" Desc="Network connection closed"/>
  <ResultCodeItem Severity="Error" CodeName="NOT_CONNECTED" Desc="Network connection is never made"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_CID" Desc="Network connection ID is invalid"/>
  <ResultCodeItem Severity="Error" CodeName="CONNECTION_TIMEOUT" Desc="Network Connection timeout"/>
  <ResultCodeItem Severity="Error" CodeName="CONNECTION_FAIL" Desc="Network connection is failed"/>
  <ResultCodeItem Severity="Error" CodeName="BADPACKET_TOOBIG" Desc="Too big packet data"/>
  <ResultCodeItem Severity="Error" CodeName="BADPACKET_NOTEXPECTED" Desc="Network Message not expected bad packet"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_MESSAGE_CHECKSUM" Desc="Checksum value of the message is invalid"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_MESSAGE_ENCRYPTION" Desc="Message encryption is invalid"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_CONNECTION_STATE" Desc="Invalid connection state"/>
  <ResultCodeItem Severity="Error" CodeName="SEQUENCE_OVERFLOW" Desc="Too big sequence id"/>
  <ResultCodeItem Severity="Error" CodeName="INTR" Desc="A blocking operation was interrupted by a call to WSACancelBlockingCall."/>
  <ResultCodeItem Severity="Error" CodeName="BADF" Desc="The file handle supplied is not valid."/>
  <ResultCodeItem Severity="Error" CodeName="ACCES" Desc="An attempt was made to access a socket in a way forbidden by its access permissions"/>
  <ResultCodeItem Severity="Error" CodeName="FAULT" Desc="The system detected an invalid pointer address in attempting to use a pointer argument in a call."/>
  <ResultCodeItem Severity="Error" CodeName="INVAL" Desc="An invalid argument was supplied."/>
  <ResultCodeItem Severity="Error" CodeName="MFILE" Desc="Too many open sockets."/>
  <ResultCodeItem Severity="Error" CodeName="WOULDBLOCK" Desc="A non-blocking socket operation could not be completed immediately."/>
  <ResultCodeItem Severity="Error" CodeName="INPROGRESS" Desc="A blocking operation is currently executing."/>
  <ResultCodeItem Severity="Error" CodeName="ALREADY" Desc="An operation was attempted on a non-blocking socket that already had an operation in progress."/>
  <ResultCodeItem Severity="Error" CodeName="NOTSOCK" Desc="An operation was attempted on something that is not a socket."/>
  <ResultCodeItem Severity="Error" CodeName="DESTADDRREQ" Desc="A required address was omitted from an operation on a socket."/>
  <ResultCodeItem Severity="Error" CodeName="NETDOWN" Desc="A socket operation encountered a dead network."/>
  <ResultCodeItem Severity="Error" CodeName="NETUNREACH" Desc="A socket operation was attempted to an unreachable network."/>
  <ResultCodeItem Severity="Error" CodeName="NETRESET" Desc="The connection has been broken due to keep-alive activity detecting a failure while the operation was in progress."/>
  <ResultCodeItem Severity="Error" CodeName="CONNABORTED" Desc="An established connection was aborted by the software in your host machine."/>
  <ResultCodeItem Severity="Error" CodeName="CONNRESET" Desc="An existing connection was forcibly closed by the remote host."/>
  <ResultCodeItem Severity="Error" CodeName="NOBUFS" Desc="An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full."/>
  <ResultCodeItem Severity="Error" CodeName="ISCONN" Desc="A connect request was made on an already connected socket."/>
  <ResultCodeItem Severity="Error" CodeName="NOTCONN" Desc="A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied."/>
  <ResultCodeItem Severity="Error" CodeName="SHUTDOWN" Desc="A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call."/>
  <ResultCodeItem Severity="Error" CodeName="TOOMANYREFS" Desc="Too many references to some kernel object."/>
  <ResultCodeItem Severity="Error" CodeName="TIMEDOUT" Desc="A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."/>
  <ResultCodeItem Severity="Error" CodeName="CONNECTION_REFUSSED" Desc="No connection could be made because the target machine actively refused it."/>
  <ResultCodeItem Severity="Error" CodeName="LOOP" Desc="Cannot translate name."/>
  <ResultCodeItem Severity="Error" CodeName="NAMETOOLONG" Desc="Name component or name was too long."/>
  <ResultCodeItem Severity="Error" CodeName="HOSTDOWN" Desc="A socket operation failed because the destination host was down."/>
  <ResultCodeItem Severity="Error" CodeName="HOSTUNREACH" Desc="A socket operation was attempted to an unreachable host."/>
  <ResultCodeItem Severity="Error" CodeName="NOTEMPTY" Desc="Cannot remove a directory that is not empty."/>
  <ResultCodeItem Severity="Error" CodeName="PROCLIM" Desc="A Windows Sockets implementation may have a limit on the number of applications that may use it simultaneously."/>
  <ResultCodeItem Severity="Error" CodeName="SYSNOTREADY" Desc="WSAStartup cannot function at this time because the underlying system it uses to provide network services is currently unavailable."/>
  <ResultCodeItem Severity="Error" CodeName="VERNOTSUPPORTED" Desc="The Windows Sockets version requested is not supported."/>
  <ResultCodeItem Severity="Error" CodeName="NOTINITIALISED" Desc="Either the application has not called WSAStartup, or WSAStartup failed."/>
  <ResultCodeItem Severity="Error" CodeName="DISCON" Desc="Returned by WSARecv or WSARecvFrom to indicate the remote party has initiated a graceful shutdown sequence."/>
  <ResultCodeItem Severity="Error" CodeName="SYSCALLFAILURE" Desc="A system call has failed."/>
  <ResultCodeItem Severity="Error" CodeName="HOST_NOT_FOUND" Desc="Host not found."/>
  <ResultCodeItem Severity="Error" CodeName="TRY_AGAIN" Desc="Try again"/>
  <ResultCodeItem Severity="Error" CodeName="IO_PENDING" Desc="IOPending"/>
  <ResultCodeItem Severity="Error" CodeName="SECURE_HOST_NOT_FOUND" Desc="No such host is known securely."/>
  <ResultCodeItem Severity="Error" CodeName="PROTO" Desc="Protocol error"/>
  <ResultCodeItem Severity="Error" CodeName="PROTOTYPE" Desc="Protocol wrong type for socket."/>
  <ResultCodeItem Severity="Error" CodeName="NOPROTOOPT" Desc="Protocol not available"/>
  <ResultCodeItem Severity="Error" CodeName="NONET" Desc="Machine is not on the network"/>
  <ResultCodeItem Severity="Error" CodeName="OPNOTSUPP" Desc="Operation not supported on socket"/>
  <ResultCodeItem Severity="Error" CodeName="BADFLAGS" Desc="An invalid value was provided for the ai_flags member of the pHints parameter."/>
  <ResultCodeItem Severity="Error" CodeName="FAMILY" Desc="Bad network family"/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_SERVICE" Desc="The pServiceName parameter is not supported for the specified ai_socktype member of the pHints parameter."/>
  <ResultCodeItem Severity="Error" CodeName="INVALID_ADDRESS" Desc="Invalid network address"/>
  <ResultCodeItem Severity="Error" CodeName="ADDRINUSE" Desc="Address in use"/>
  <ResultCodeItem Severity="Error" CodeName="BADPACKET" Desc="Network Message not expected packet data"/>
  <ResultCodeItem Severity="Error" CodeName="DISCONNECTED" Desc="Disconnected"/>

</ResultCodes>

=== StormForgeDeveloper/StormForge/Engine/Data/ResultCode/ResultCodeEngine.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ResultCodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="SFResultCode.xsd"
             Facility="Engine"
             IDTable="false"
             >


	<ResultCodeItem Severity="Error" CodeName="INITIALIZATION_FAILED" Desc="Engine initialization is failed"/>
	<ResultCodeItem Severity="Error" CodeName="INVALID_CONFIG" Desc="Invalid configuration"/>
	<ResultCodeItem Severity="Error" CodeName="CONNECTION_FAILED" Desc="Connection failed"/>
	<ResultCodeItem Severity="Error" CodeName="CONNECTION_LOST" Desc="Connectionlost"/>

	<ResultCodeItem Severity="Error" CodeName="INVALID_CHARACTER" Desc="Invalid character data"/>
	
	<ResultCodeItem Severity="Error" CodeName="INVALID_TABLE_ID" Desc="Invalid table id"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_PLATFORM" Desc="Invalid platform"/>
    <ResultCodeItem Severity="Error" CodeName="ALREADY_USED_ITEM" Desc="Already Used Item"/>
    <ResultCodeItem Severity="Error" CodeName="ALREADY_USED_KEY" Desc="Already Used Key"/>

    <ResultCodeItem Severity="Error" CodeName="INVALID_ONLINE_SESSION" Desc="Invalid online session. probably kicked/expired"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_SESSION_TOKEN" Desc="Invalid session token. probably dupe login"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_GAME_SESSION" Desc="Invalid session GameUID. probably dupe login"/>

    <ResultCodeItem Severity="Error" CodeName="INVALIDD_TITLE_GUID" Desc="Invalid title guid"/>
    <ResultCodeItem Severity="Error" CodeName="INVALIDD_TITLE_ENV" Desc="Invalid titile env"/>


</ResultCodes>

=== StormForgeDeveloper/StormForge/Engine/Data/ResultCode/ResultCodeLogin.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ResultCodes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:noNamespaceSchemaLocation="SFResultCode.xsd"
             Facility="Login"
             IDTable="true"
             >


    <ResultCodeItem Severity="Error" CodeName="INVALID_USERNAME" Desc="Invalid username"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_PASSWORD" Desc="Invalid password"/>
    <ResultCodeItem Severity="Error" CodeName="ALREADY_LOGGEDIN" Desc="Already logged in"/>
    <ResultCodeItem Severity="Error" CodeName="ALREADY_LOGGEDIN_OTHERPLACE" Desc="Already logged in at another place, and failed to kick"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_SIGNATURE" Desc="Invalid user signature"/>
    <ResultCodeItem Severity="Error" CodeName="NO_APP_OWNERSHIP" Desc="The user doesn't have app ownership"/>
    <ResultCodeItem Severity="Error" CodeName="ACCOUNT_BLOCKED" Desc="The user is blocked"/>
    <ResultCodeItem Severity="Error" CodeName="ACCOUNT_DOES_NOT_EXIST" Desc="The user is not exist"/>
    <ResultCodeItem Severity="Error" CodeName="INVALID_PLATFORM_LOGIN" Desc="The user's platform login is invalid"/>
    <ResultCodeItem Severity="Error" CodeName="NOT_ENOUGH_PRIVILEDGE" Desc="The user doesn't have enough priviledge"/>

</ResultCodes>
