=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolTypeDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.StormForge.com/XMLProtocol" targetNamespace="http://www.StormForge.com/XMLProtocol" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="ProtocolTypes">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="DataType" maxOccurs="unbounded">
					<xs:complexType>
						<xs:attribute name="TypeName" type="xs:string" use="required"/>
						<xs:attribute name="IsEnum" type="xs:boolean" use="required"/>
						<xs:attribute name="CppTypeName" type="xs:string" use="required"/>
						<xs:attribute name="CppTypeForward" type="xs:string" use="required"/>
						<xs:attribute name="CppTypeInclude" type="xs:string" use="required"/>
						<xs:attribute name="IsVariableSize" type="xs:boolean" use="required"/>
						<xs:attribute name="CSharpTypeName" type="xs:string" use="required"/>
						<xs:attribute name="IsCSharpStruct" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="IsCSharpArray" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="UseGenericVariableBuilderInterface" type="xs:boolean" use="optional" default="true"/>
						<xs:attribute name="Desc" type="xs:string" use="optional"/>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolTypes.xml
<?xml version="1.0" encoding="UTF-8"?>
<ProtocolTypes xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ProtocolTypeDef.xsd">
	<DataType TypeName="ActorMovement" IsEnum="false" CppTypeName="ActorMovement" IsVariableSize="false" CSharpTypeName="ActorMovement" IsCSharpStruct="true" IsCSharpArray="false" Desc="ActorMovement struct"/>
	<DataType TypeName="PlayerPlatformID" IsEnum="false" CppTypeName="PlayerPlatformID" IsVariableSize="false" CSharpTypeName="PlayerPlatformID" IsCSharpStruct="true" IsCSharpArray="false" Desc="Unified player ID cross multiplatform"/>
    <DataType TypeName="AchievementStat" IsEnum="false" CppTypeName="AchievementStat" IsVariableSize="false" CSharpTypeName="AchievementStat" IsCSharpStruct="true" IsCSharpArray="false" Desc="AchievementStat struct"/>
    <DataType TypeName="LogEntryID" IsEnum="false" CppTypeName="uint32_t" IsVariableSize="false" CSharpTypeName="UInt32" IsCSharpStruct="false" IsCSharpArray="false" Desc="32bit log entry id assigned by system"/>
    <DataType TypeName="UGCID" IsEnum="false" CppTypeName="uint64_t" IsVariableSize="false" CSharpTypeName="UInt64" IsCSharpStruct="false" IsCSharpArray="false" Desc="64bit UGC content id assigned by system"/>
    <DataType TypeName="EAccountRole" IsEnum="false" CppTypeName="EAccountRole" IsVariableSize="false" CSharpTypeName="EAccountRole" IsCSharpStruct="false" IsCSharpArray="false" Desc="Account role"/>
    <DataType TypeName="Quaternion" IsEnum="false" CppTypeName="Quaternion" IsVariableSize="false" CSharpTypeName="Quaternion" IsCSharpStruct="true" IsCSharpArray="false" Desc="Quaternion struct"/>
</ProtocolTypes>
