=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolDef.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns1="http://www.StormForge.com/XMLProtocol" targetNamespace="http://www.StormForge.com/XMLProtocol" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Protocols">
		<xs:annotation>
			<xs:documentation>root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ProtocolGroup" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Protocol Group</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:choice minOccurs="0" maxOccurs="unbounded">
								<xs:element name="Command" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Command</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="MessageBase">
												<xs:all>
													<xs:element name="Cmd">
														<xs:annotation>
															<xs:documentation>Command parts</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Params" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="Res">
														<xs:annotation>
															<xs:documentation>Resule of command</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:sequence>
																<xs:element name="Params" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:all>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="C2SEvent" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Client to Server Event </xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="MessageBase">
												<xs:sequence>
													<xs:element name="Params" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="S2CEvent" minOccurs="0">
									<xs:annotation>
										<xs:documentation>Server to client Event </xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:complexContent>
											<xs:extension base="MessageBase">
												<xs:sequence>
													<xs:element name="Params" type="Parameter" minOccurs="0" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:extension>
										</xs:complexContent>
									</xs:complexType>
								</xs:element>
							</xs:choice>
						</xs:sequence>
						<xs:attribute name="Name" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Protocol Name</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="GenParameterContext" type="xs:boolean" use="optional" default="true">
							<xs:annotation>
								<xs:documentation>No default context parameter</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="GenParameterRouteContext" type="xs:boolean" use="optional" default="false">
							<xs:annotation>
								<xs:documentation>Description</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="IsMobile" type="xs:boolean" use="optional" default="false"/>
						<xs:attribute name="IsServer" type="xs:boolean" use="optional" default="false">
							<xs:annotation>
								<xs:documentation>Is server policy</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="GenParameterRouteHopCount" type="xs:boolean" use="optional" default="false"/>

						<xs:attribute name="GenNet" type="xs:boolean" use="optional" default="false">
							<xs:annotation>
								<xs:documentation>Generate Net Policy</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="GenCSharp" type="xs:boolean" use="optional" default="false">
							<xs:annotation>
								<xs:documentation>Generate CSharp</xs:documentation>
							</xs:annotation>
						</xs:attribute>
						<xs:attribute name="Desc" type="xs:string" use="required">
							<xs:annotation>
								<xs:documentation>Description</xs:documentation>
							</xs:annotation>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Parameter">
		<xs:annotation>
			<xs:documentation>Message parameter</xs:documentation>
		</xs:annotation>
		<xs:attribute name="Name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Name of Parameter</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="TypeName" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Type of parameter</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="IsArray" type="xs:boolean" use="optional">
			<xs:annotation>
				<xs:documentation>TRUE for Array parameter</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Desc" type="xs:string" use="optional">
			<xs:annotation>
				<xs:documentation>Description</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="MessageBase">
		<xs:attribute name="Name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Message Name</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="Reliable" type="xs:boolean" use="required"/>
		<xs:attribute name="Crypto" use="required">
			<xs:annotation>
				<xs:documentation>Encryption method</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="No"/>
					<xs:enumeration value="Mask"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Trace" use="required">
			<xs:annotation>
				<xs:documentation>Debug trace channel</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:whiteSpace value="preserve"/>
					<xs:enumeration value="Debug"/>
					<xs:enumeration value="Debug1"/>
					<xs:enumeration value="Debug2"/>
					<xs:enumeration value="Debug3"/>
          <xs:enumeration value="Debug4"/>
          <xs:enumeration value="Debug5"/>
          <xs:enumeration value="Debug6"/>
					<xs:enumeration value=""/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
    <xs:attribute name="Usage" use="optional" default="None">
      <xs:annotation>
        <xs:documentation>Message usage</xs:documentation>
      </xs:annotation>
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:enumeration value="None"/>
          <xs:enumeration value="ClusterDataRead"/>
          <xs:enumeration value="ClusterDataWrite"/>
          <xs:enumeration value="ClusterStatusRead"/>
          <xs:enumeration value="ClusterStatusWrite"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="Checksum" use="optional" default="NONE">
			<xs:annotation>
				<xs:documentation>Checksum type</xs:documentation>
			</xs:annotation>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="NONE"/>
					<xs:enumeration value="CRC32"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
		<xs:attribute name="Desc" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>Description</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolPlayInstance.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocols xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ../../StormForge/Engine/Data/Protocol/ProtocolDef.xsd">
	<ProtocolGroup Name="PlayInstance" IsMobile="false" GenCSharp="true" Desc="PlayInstance Protocol">

    <!-- ============================  Game instance ============================================ -->

	<Command Name="JoinGameInstance" Reliable="true" Crypto="No" Trace="Debug1" Desc="Event for Player Join request.">
		<Cmd>
			<Params Type="EntityUID" Name="PlayInstanceID" Desc="Play instance to join"/>
			<Params Type="PlayerID" Name="PlayerID" Desc="Joining player id"/>
			<Params Type="String" Name="PlayerIdentifier" Desc="Joining player identifier. string value"/>
		</Cmd>
		<Res>
			<Params Type="EntityUID" Name="PlayInstanceID" Desc="joined Play instance ID"/>
			<Params Type="uint32" Name="MyEndpointID" Desc="Joined player PlayID"/>
			<Params Type="PlayerInformation" IsArray="true" Name="MemberInfos" Desc="Member player IDs"/>
		</Res>
	</Command>


	<S2CEvent Name="PlayerJoined" Reliable="true" Crypto="No" Trace="Debug1" Desc="Event for Player joined.">
		<Params Type="uint32" Name="PlayInstanceID" Desc="Play Instance id"/>
		<Params Type="PlayerInformation" Name="JoinedPlayerInfo" Desc="Joined player ID"/>
	</S2CEvent>

	<S2CEvent Name="PlayerLeft" Reliable="true" Crypto="No" Trace="Debug1" Desc="Event for Player left.">
		<Params Type="uint32" Name="PlayInstanceID" Desc="Play Instance id"/>
		<Params Type="PlayerID" Name="LeftPlayerID" Desc="Left player ID"/>
		<Params Type="uint32" Name="KickedReason" Desc="Reason"/>
	</S2CEvent>

	<S2CEvent Name="PlayerKicked" Reliable="true" Crypto="No" Trace="Debug1" Desc="Player kicked event. this event will be brocasted when a player kicked.">
		<Params Type="PlayerID" Name="KickedPlayerID" Desc="Kicked player ID"/>
	</S2CEvent>

	<C2SEvent Name="PlayPacket" Reliable="false" Crypto="No" Trace="Debug1" Desc="Play packet">
		<Params Type="uint32" Name="PlayInstanceID" Desc="Play Instance id"/>
		<Params Type="uint32" Name="SenderEndpointID" Desc="Sender player ID"/>
		<Params Type="uint32" Name="TargetEndpointMask" Desc="Target Play mask."/>
		<Params Type="uint8" IsArray="true" Name="Payload" Desc="Payload data"/>
	</C2SEvent>


    <!-- ============================= Player movement  ======================================= -->


		<S2CEvent Name="NewPlayerInView" Reliable="true" Crypto="No" Trace="Debug1" Desc="New Player in get view">
			<Params Type="GameInsUID" Name="GameInsUID" Desc="Game instance UID"/>
			<Params Type="PlayerID" Name="PlayerID" Desc="Player Id"/>
			<Params Type="VariableTable" Name="Attributes" Desc="Movement attributes"/>
		</S2CEvent>

		<S2CEvent Name="RemovePlayerFromView" Reliable="true" Crypto="No" Trace="Debug1" Desc="Remove player from view">
			<Params Type="GameInsUID" Name="GameInsUID" Desc="Game instance UID"/>
			<Params Type="PlayerID" Name="PlayerID" Desc="Player Id"/>
			<Params Type="VariableTable" Name="Attributes" Desc="Movement attributes"/>
		</S2CEvent>


		<C2SEvent Name="PlayerMovement" Reliable="true" Crypto="No" Trace="Debug1" Desc="Player Movement">
			<Params Type="GameInsUID" Name="GameInsUID" Desc="Game instance UID"/>
			<Params Type="PlayerID" Name="PlayerID" Desc="Player Id"/>
			<Params Type="VariableTable" Name="Attributes" Desc="Movement attributes"/>
		</C2SEvent>

		<S2CEvent Name="PlayerMovement" Reliable="true" Crypto="No" Trace="Debug1" Desc="Player Movement">
			<Params Type="GameInsUID" Name="GameInsUID" Desc="Game instance UID"/>
			<Params Type="PlayerID" Name="PlayerID" Desc="Player Movement"/>
			<Params Type="VariableTable" Name="Attributes" Desc="Movement attributes"/>
		</S2CEvent>



		<!-- ============================  Streaming ============================================ -->

    <Command Name="CreateStream" Reliable="true" Crypto="No" Trace="Debug1" Desc="Create stream instance">
      <Cmd>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
        <Params Type="String" Name="StreamName" Desc="Stream name"/>
      </Cmd>
      <Res>
        <Params Type="NetAddress" Name="StreamServerAddr" Desc="Stream server address to connect"/>
        <Params Type="NetAddress" Name="StreamServerAddrIPV4" Desc="Stream server address to connect"/>
        <Params Type="String" Name="StreamUID" Desc="Unique stream Id generated by server. This wil be used when you operate streaming"/>
      </Res>
    </Command>

    <Command Name="FindStream" Reliable="true" Crypto="No" Trace="Debug1" Desc="Open stream instance">
      <Cmd>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
        <Params Type="String" Name="StreamName" Desc="Stream name"/>
      </Cmd>
      <Res>
        <Params Type="NetAddress" Name="StreamServerAddr" Desc="Stream server address to connect"/>
        <Params Type="NetAddress" Name="StreamServerAddrIPV4" Desc="Stream server address to connect"/>
        <Params Type="String" Name="StreamUID" Desc="Unique stream Id generated by server. This wil be used when you operate streaming"/>
      </Res>
    </Command>

    <Command Name="DeleteStream" Reliable="true" Crypto="No" Trace="Debug1" Desc="Delete stream instance">
      <Cmd>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
        <Params Type="String" Name="StreamName" Desc="stream name to delete"/>
      </Cmd>
      <Res>
      </Res>
    </Command>

    <Command Name="GetStreamList" Reliable="true" Crypto="No" Trace="Debug1" Desc="Get stream list">
      <Cmd>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
      </Cmd>
      <Res>
        <Params Type="String" Name="StreamNames" IsArray="true" Desc="Stream names"/>
      </Res>
    </Command>

	<!-- <C2SEvent Name="NewStreamPacket" Reliable="true" Crypto="No" Trace="Debug1" Desc="Play packet"> -->
        <!-- <Params Type="String" Name="StreamUID" Desc="Unique stream Id to delete"/> -->
		<!-- <Params Type="uint32" Name="SenderEndpointID" Desc="Sender player ID"/> -->
		<!-- <Params Type="uint32" Name="TargetEndpointMask" Desc="Target Play mask."/> -->
		<!-- <Params Type="uint8" IsArray="true" Name="Payload" Desc="Payload data"/> -->
	<!-- </C2SEvent> -->


	<!-- <S2CEvent Name="StreamPacket" Reliable="true" Crypto="No" Trace="Debug1" Desc="Event for Player left."> -->
		<!-- <Params Type="uint32" Name="PlayInstanceID" Desc="Play Instance id"/> -->
		<!-- <Params Type="PlayerID" Name="LeftPlayerID" Desc="Left player ID"/> -->
		<!-- <Params Type="uint32" Name="KickedReason" Desc="Reason"/> -->
	<!-- </S2CEvent> -->



    <!-- =============================  ======================================= -->

	</ProtocolGroup>
</Protocols>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolLogin.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocols xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ProtocolDef.xsd">
	<ProtocolGroup Name="Login" GenParameterContext="true" IsMobile="true" GenCSharp="true" Desc="Game">
	
    <!-- ===================================================  Login ========================================================= -->
    <Command Name="Login" Reliable="true" Crypto="No" Trace="Debug1" Desc="Login request">
      <Cmd>
        <Params Type="GameID" Name="GameID" Desc="Game ID, Conspiracy will be accepted"/>
        <Params Type="String" Name="ID" Desc="UserID"/>
        <Params Type="String" Name="Password" Desc="User Password"/>
      </Cmd>
      <Res>
        <Params Type="NetAddress" Name="GameServerAddr" Desc="Game server address to connect"/>
        <Params Type="NetAddress" Name="GameServerAddrIPV4" Desc="Game server address to connect"/>
        <Params Type="AccountID" Name="AccID" Desc="AccountID for the player"/>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
    		<Params Type="uint64" Name="LoginEntityUID" Desc="Login entity ID. This need to be used when you connect to the game server"/>
      </Res>
    </Command>
    <Command Name="LoginByFacebook" Reliable="true" Crypto="No" Trace="Debug1" Desc="Login request with Facebook UID">
      <Cmd>
        <Params Type="GameID" Name="GameID" Desc="Game ID, Conspiracy will be accepted"/>
        <Params Type="uint64" Name="UID" Desc="Facebook UID. You can get when you login to facebook"/>
        <Params Type="String" Name="FaceBookName" Desc="Face book name"/>
        <Params Type="String" Name="EMail" Desc="email address of the player"/>
        <Params Type="String" Name="FacebookToken" Desc="Factbook token, reserved"/>
      </Cmd>
      <Res>
        <Params Type="NetAddress" Name="GameServerAddr" Desc="Game server address to connect"/>
        <Params Type="NetAddress" Name="GameServerAddrIPV4" Desc="Game server address to connect"/>
        <Params Type="AccountID" Name="AccID" Desc="AccountID for the player"/>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
        <Params Type="uint64" Name="LoginEntityUID" Desc="Login entity ID. This need to be used when you connect to the game server"/>
      </Res>
    </Command>

    <Command Name="CreateRandomUser" Reliable="true" Crypto="No" Trace="Debug1" Desc="Login request">
      <Cmd>
        <Params Type="GameID" Name="GameID" Desc="Game ID, Conspiracy will be accepted"/>
        <Params Type="String" Name="CellPhone" Desc="CellPhone"/>
      </Cmd>
      <Res>
        <Params Type="NetAddress" Name="GameServerAddr" Desc="Game server address to connect"/>
        <Params Type="NetAddress" Name="GameServerAddrIPV4" Desc="Game server address to connect"/>
        <Params Type="AccountID" Name="AccID" Desc="AccountID for the player"/>
        <Params Type="AuthTicket" Name="Ticket" Desc="Login session Ticket"/>
        <Params Type="uint64" Name="LoginEntityUID" Desc="Login entity ID. This need to be used when you connect to the game server"/>
      </Res>
    </Command>

	
	
    <Command Name="UpdateMyScore" Reliable="true" Crypto="No" Trace="Debug1" Desc="Update my score and Get Ranking list">
      <Cmd>
        <Params Type="uint64" Name="RankingScore"/>
        <Params Type="RankingType" Name="RankingType"/>
        <Params Type="uint16" Name="Count" Desc="Number of ranking list to query after update"/>
      </Cmd>
      <Res>
        <Params Type="TotalRankingPlayerInformation" Name="Ranking" IsArray="true"/>
      </Res>
    </Command>

    <Command Name="GetRankingList" Reliable="true" Crypto="No" Trace="Debug1" Desc="Get Ranking lise">
      <Cmd>
        <Params Type="RankingType" Name="RankingType"/>
        <Params Type="uint8" Name="BaseRanking" Desc="Base ranking to query, 0 based ranking order"/>
        <Params Type="uint8" Name="Count" Desc="Number of playerinformation to query"/>
      </Cmd>
      <Res>
        <Params Type="TotalRankingPlayerInformation" Name="Ranking" IsArray="true"/>
      </Res>
    </Command>

    <Command Name="DataTest" Reliable="true" Crypto="No" Trace="Debug1" Desc="For network test">
      <Cmd>
        <Params Type="uint8" Name="TestData" IsArray="true"/>
      </Cmd>
      <Res>
        <Params Type="uint8" Name="TestData" IsArray="true"/>
      </Res>
    </Command>
	
	
	<C2SEvent Name="Heartbeat" Reliable="true" Crypto="No" Trace="Debug1" Desc="Heartbeat">
    </C2SEvent>

    <Command Name="DebugPrintALLRanking" Reliable="true" Crypto="No" Trace="Debug1" Desc="Write All!! User Score and Ranking list">
      <Cmd>
        <Params Type="String" Name="FileName"/>
      </Cmd>
      <Res>
      </Res>
    </Command>
    
  </ProtocolGroup>
</Protocols>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolTelemetry.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocols xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ../../../StormForge/Engine/Data/Protocol/ProtocolDef.xsd">
  <ProtocolGroup Name="Telemetry" sMobile="false" Desc="Telemetry Protocol">
    <!-- ============================  Telemetry ============================================ -->

      <Command Name="PostEvent" Reliable="true" Crypto="No" Trace="Debug1" Desc="Post telemetry event">
          <Cmd>
			<Params TypeName="String" Name="EventName" Desc="Name of the event"/>
			<Params TypeName="uint64" Name="TimeStamp" Desc="Linux UCT time64_t"/>
			<Params TypeName="String" Name="AppID" Desc="Application Id, alternatively GameID"/>
			<Params TypeName="String" Name="MachineID" Desc="Machine unique Id"/>
			<Params TypeName="uint32" Name="EventID" Desc="event unique Id assigned by client"/>
			<Params TypeName="AccountID" Name="AccountID" Desc="AccountId"/>
			<Params TypeName="bool" Name="IsPlayEvent" Desc="true if it is a play event"/>
			<Params TypeName="uint8" IsArray="true" Name="SessionID" Desc="Session Id, UUID byte stream"/>
			<Params TypeName="NamedVariable" IsArray="true" Name="Attributes" Desc="Attributes, array of named variables"/>
          </Cmd>
          <Res>
          </Res>
      </Command>

  </ProtocolGroup>
</Protocols>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/Generic.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocols xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ../../../StormForge/Engine/Data/Protocol/ProtocolDef.xsd">
  <ProtocolGroup Name="Generic" Desc="Generic Protocol">
    <!-- ============================  Server Generic  ============================================ -->

      <Command Name="GenericFailure" Reliable="true" Crypto="No" Trace="Debug1" Desc="Generic failure message">
          <Cmd>
          </Cmd>
          <Res>
          </Res>
      </Command>

      <Command Name="GenericTransaction" Reliable="true" Crypto="No" Trace="Debug1" Desc="Generic transaction result">
          <Cmd>
          </Cmd>
          <Res>
              <Params TypeName="TransactionID" Name="FinishedTransaction" Desc="TransactionId"/>
			  <Params TypeName="String" Name="Signature" Desc="Transaction signature"/>
          </Res>
      </Command>

  </ProtocolGroup>
</Protocols>

=== StormForgeDeveloper/StormForge/Engine/Data/Protocol/ProtocolRelay.xml
<?xml version="1.0" encoding="UTF-8"?>
<Protocols xmlns="http://www.StormForge.com/XMLProtocol" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.StormForge.com/XMLProtocol ../../StormForge/Engine/Data/Protocol/ProtocolDef.xsd">
	<ProtocolGroup Name="Relay" IsMobile="false" Desc="Relay Protocol">

    <!-- ============================  Relay ============================================ -->

	<C2SEvent Name="JoinRelayInstance" Reliable="false" Crypto="No" Trace="Debug1" Desc="Event for Player Join request.">
		<Params Type="PlayerID" Name="PlayerID" Desc="Joining player id"/>
	</C2SEvent>

	<S2CEvent Name="JoinRelayInstanceRes" Reliable="false" Crypto="No" Trace="Debug1" Desc="Event for joined player">
		<Params Type="Result" Name="Result" Desc="Join result"/>
		<Params Type="RelayPlayerInfo" Name="MyPlayerInfo" Desc="Joined player info"/>
		<Params Type="uint32" Name="RelayInstanceID" Desc="joined relay instance ID"/>
		<Params Type="RelayPlayerInfo" IsArray="true" Name="MemberInfos" Desc="Member player IDs"/>
	</S2CEvent>

	<C2SEvent Name="LeaveRelayInstance" Reliable="false" Crypto="No" Trace="Debug1" Desc="Event for Player Join request.">
		<Params Type="uint32" Name="RelayInstanceID" Desc="Relay Instance id"/>
		<Params Type="PlayerID" Name="PlayerID" Desc="player id"/>
	</C2SEvent>


	<S2CEvent Name="PlayerJoin" Reliable="false" Crypto="No" Trace="Debug1" Desc="Event for Player joined.">
		<Params Type="uint32" Name="RelayInstanceID" Desc="Relay Instance id"/>
		<Params Type="RelayPlayerInfo" Name="JoinedPlayerInfo" Desc="Joined player ID"/>
	</S2CEvent>

	<S2CEvent Name="PlayerLeft" Reliable="false" Crypto="No" Trace="Debug1" Desc="Event for Player left.">
		<Params Type="uint32" Name="RelayInstanceID" Desc="Relay Instance id"/>
		<Params Type="PlayerID" Name="LeftPlayerID" Desc="Left player ID"/>
		<Params Type="uint32" Name="KickedReason" Desc="Reason"/>
	</S2CEvent>


	<C2SEvent Name="RelayPacket" Reliable="false" Crypto="No" Trace="Debug1" Desc="Relay packet">
		<Params Type="uint32" Name="RelayInstanceID" Desc="Relay Instance id"/>
		<Params Type="uint64" Name="SenderRelayID" Desc="Sender player ID"/>
		<Params Type="uint64" Name="TargetRelayMask" Desc="Target relay mask."/>
	</C2SEvent>


    <!-- =============================  ======================================= -->

	</ProtocolGroup>
</Protocols>
